// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
#include "reducer.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `component:reducewc/reduce`

__attribute__((__weak__, __export_name__("cabi_post_component:reducewc/reduce#reduce")))
void __wasm_export_exports_component_reducewc_reduce_reduce_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + 4))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + 12))) > 0) {
    free(*((uint8_t **) (arg0 + 8)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void reducer_list_string_free(reducer_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    reducer_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      reducer_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void reducer_tuple2_string_string_free(reducer_tuple2_string_string_t *ptr) {
  reducer_string_free(&ptr->f0);
  reducer_string_free(&ptr->f1);
}

void reducer_string_set(reducer_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void reducer_string_dup(reducer_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void reducer_string_free(reducer_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[16];

__attribute__((__export_name__("component:reducewc/reduce#reduce")))
uint8_t * __wasm_export_exports_component_reducewc_reduce_reduce(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  reducer_string_t arg3 = (reducer_string_t) { (uint8_t*)(arg), (arg0) };
  reducer_list_string_t arg4 = (reducer_list_string_t) { (reducer_string_t*)(arg1), (arg2) };
  reducer_tuple2_string_string_t ret;
  exports_component_reducewc_reduce_reduce(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = ((ret).f0).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).f0).ptr;
  *((size_t*)(ptr + 12)) = ((ret).f1).len;
  *((uint8_t **)(ptr + 8)) = (uint8_t *) ((ret).f1).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_reducer(void);
void __component_type_object_force_link_reducer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_reducer();
}
