// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
#ifndef __BINDINGS_REDUCER_H
#define __BINDINGS_REDUCER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct reducer_string_t {
  uint8_t*ptr;
  size_t len;
} reducer_string_t;

typedef struct {
  reducer_string_t *ptr;
  size_t len;
} reducer_list_string_t;

typedef struct {
  reducer_string_t f0;
  reducer_string_t f1;
} reducer_tuple2_string_string_t;

// Exported Functions from `component:reducewc/reduce`
void exports_component_reducewc_reduce_reduce(reducer_string_t *key, reducer_list_string_t *values, reducer_tuple2_string_string_t *ret);

// Helper Functions

void reducer_list_string_free(reducer_list_string_t *ptr);

void reducer_tuple2_string_string_free(reducer_tuple2_string_string_t *ptr);

// Transfers ownership of `s` into the string `ret`
void reducer_string_set(reducer_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void reducer_string_dup(reducer_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void reducer_string_free(reducer_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
